import turtle
turtle.setup(width=950, height=800, startx=10, starty=-10)    
turtle.title('Magyar zászló2')
t = turtle.Turtle()
t.pen(pensize=2,fillcolor="red",pencolor="red",speed=7)
t.begin_fill()
t.penup()
t.setposition(x=-400, y=300)
t.pendown()
for i in range(2):
    t.forward(800)
    t.right(90)
    t.forward(135)
    t.right(90)
t.end_fill()
t.pen(fillcolor="green", pencolor="black",speed=7)
t.begin_fill()
t.penup()
t.setposition(x=-400, y=30)
t.pendown()
for i in range(2):
    t.forward(800)
    t.right(90)
    t.forward(135)
    t.right(90)
t.end_fill()
t.penup()
t.setposition(x=-400, y=300)
t.pendown()
for i in range(2):
    t.forward(800)
    t.right(90)
    t.forward(405)
    t.right(90)